print("My name is Jeremiah.")
print("I am 16 years old.")
print("My favorite game is Roblox")
print("My favorite food is Burgers")
print("I'm learning to code because I want to make scripts, and programs for games.")
print(5)
print(10 + 5)
print(20 - 7)
print(4 * 3)
print(20 / 4)